In [29]:
import matplotlib.pyplot as plt
import numpy  as np
import pandas as pd
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
pd.options.display.max_columns = None

In [5]:
housing = pd.read_csv('../data/Ames_Housing_Price_Data.csv', index_col = 0)
real_estate = pd.read_csv('../data/Ames_Real_Estate_Data.csv', index_col = 0)
house_df = pd.read_csv('../data/final_df.csv', index_col = 0)

In [25]:
housing3 = pd.concat([housing[housing.columns[53:]],housing['SalePrice']],axis=1)
housing3

,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1,1,TA,4,Typ,1,Gd,Detchd,1939.0,Unf,2.0,...,0,NaN,NaN,NaN,0,3,2010,WD,Normal,126000
2,1,Gd,5,Typ,0,NaN,Attchd,1984.0,Fin,1.0,...,0,NaN,NaN,NaN,0,2,2009,WD,Normal,139500
3,1,Gd,5,Typ,0,NaN,Detchd,1930.0,Unf,1.0,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,124900
4,1,TA,6,Typ,0,NaN,Detchd,1940.0,Unf,1.0,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,114000
5,1,Gd,6,Typ,0,NaN,Attchd,2001.0,Fin,2.0,...,0,NaN,NaN,NaN,0,11,2009,WD,Normal,227000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
759,1,Fa,4,Typ,1,Gd,Detchd,1916.0,Unf,1.0,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,121000
760,1,TA,8,Min2,1,Gd,Attchd,1955.0,Unf,2.0,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,139600
761,2,TA,8,Typ,0,NaN,2Types,1949.0,Unf,3.0,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,145000
762,1,Gd,7,Typ,1,TA,Attchd,2000.0,Fin,2.0,...,0,NaN,NaN,NaN,0,7,2007,WD,Normal,217500
763,1,Gd,8,Typ,1,TA,Attchd,1993.0,RFn,2.0,...,0,NaN,NaN,NaN,0,9,2006,WD,Normal,215000

In [26]:
house_features = housing3.drop(['SalePrice'],axis=1)
price = housing3['SalePrice']

In [34]:
house_features.columns

Index(['KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional',
       'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition'],
      dtype='object')

In [8]:
len(house_df.columns)

179

In [11]:
X = house_df.drop('SalePrice',axis=1)

In [41]:
X['PoolQC']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
2402    NaN
2403    NaN
2404    NaN
2405    NaN
2406    NaN
Name: PoolQC, Length: 2407, dtype: object

In [71]:
X.shape

(2407, 173)

### Droping PoolArea, PoolQC, Fence, MiscFeature, MiscVal will be drop due to too many missing value

In [44]:
# X= X.drop(['PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal'], axis=1)
len(X.columns)

173

In [76]:
house_df.isnull().sum()

index                0
PID                  0
GrLivArea            0
SalePrice            0
Distance            23
                    ..
ISU_lat_long         0
lat_long             0
ISU_lat              0
ISU_long             0
address_lat_long     0
Length: 179, dtype: int64

In [84]:
house_df_test = house_df.copy()
house_df_test.isnull().sum(axis=1)

0       27
1       26
2       26
3       27
4       24
        ..
2402    25
2403    25
2404    34
2405    25
2406    28
Length: 2407, dtype: int64

In [85]:
house_df_test = house_df.copy()
house_df_test.isnull().sum(axis=0)

index                0
PID                  0
GrLivArea            0
SalePrice            0
Distance            23
                    ..
ISU_lat_long         0
lat_long             0
ISU_lat              0
ISU_long             0
address_lat_long     0
Length: 179, dtype: int64

In [79]:
# for feature2 in X.columns:
#     print(house_df[X].isnull().value_counts())
#     print('*'*30)
    
house_df[house_df.isnull().sum()>0]

D:\software\Anaconda\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

In [66]:
house_df[X].isnull().value_counts()

ValueError: Boolean array expected for the condition, not int64

In [14]:
X_features = pd.get_dummies(X, drop_first=False, dummy_na=True)
y = house_df['SalePrice']

In [13]:
len(X_features.columns)

24134

In [39]:
X_features['PoolQC']

KeyError: 'PoolQC'

### feature selection with lasso

In [38]:
X_features = X_features.drop(['PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal'], axis=1)

KeyError: "['PoolQC' 'Fence' 'MiscFeature'] not found in axis"

In [31]:
X.info

<bound method DataFrame.info of       index        PID  GrLivArea  Distance  MSSubClass MSZoning  LotFrontage  \
0         0  909176150        856  7.846880          30       RL          NaN
1         1  905476230       1049  1.446325         120       RL         42.0
2         2  905476230       1049  1.446325         120       RL         42.0
3         3  911128020       1001  2.740599          30  C (all)         60.0
4         4  535377150       1039  3.050284          70       RL         80.0
...     ...        ...        ...       ...         ...      ...          ...
2402   2618  908128100       1724  2.351819          60       RL         62.0
2403   2619  903205040        952  1.747982          30       RL          NaN
2404   2620  905402060       1733  1.765919          20       RL          NaN
2405   2622  907192040       1842  3.756711          60       RL          NaN
2406   2623  906223180       1911  3.001349          60       RL         80.0

      LotArea Street Alley LotShape LandContour Utilities LotConfig LandSlope  \
0        7890   Pave   NaN      Reg         Lvl    AllPub    Corner       Gtl
1        4235   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
2        4235   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
3        6060   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
4        8146   Pave   NaN      Reg         Lvl    AllPub    Corner       Gtl
...       ...    ...   ...      ...         ...       ...       ...       ...
2402     7162   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
2403     8854   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
2404    13680   Pave   NaN      IR1         Lvl    AllPub   CulDSac       Gtl
2405     8826   Pave   NaN      Reg         Lvl    AllPub    Inside       Gtl
2406     9554   Pave   NaN      IR1         Lvl    AllPub    Inside       Gtl

     Neighborhood Condition1 Condition2 BldgType HouseStyle  OverallQual  \
0           SWISU       Norm       Norm     1Fam     1Story            6
1         Edwards       Norm       Norm   TwnhsE     1Story            5
2         Edwards       Norm       Norm   TwnhsE     1Story            5
3          IDOTRR       Norm       Norm     1Fam     1Story            5
4         OldTown       Norm       Norm     1Fam     2Story            4
...           ...        ...        ...      ...        ...          ...
2402      Edwards       Norm       Norm     1Fam     2Story            7
2403      BrkSide       Norm       Norm     1Fam     1.5Unf            6
2404      Edwards       Norm       Norm     1Fam     1Story            3
2405      CollgCr       Norm       Norm     1Fam     2Story            7
2406      SawyerW       Norm       Norm     1Fam     2Story            8

      OverallCond  YearBuilt  YearRemodAdd RoofStyle RoofMatl Exterior1st  \
0               6       1939          1950     Gable  CompShg     Wd Sdng
1               5       1984          1984     Gable  CompShg     HdBoard
2               5       1984          1984     Gable  CompShg     HdBoard
3               9       1930          2007       Hip  CompShg     MetalSd
4               8       1900          2003     Gable  CompShg     MetalSd
...           ...        ...           ...       ...      ...         ...
2402            5       2003          2004       Hip  CompShg     HdBoard
2403            6       1916          1950     Gable  CompShg     Wd Sdng
2404            5       1955          1955       Hip  CompShg     BrkFace
2405            5       2000          2000     Gable  CompShg     VinylSd
2406            5       1993          1994     Gable  CompShg     VinylSd

     Exterior2nd MasVnrType  MasVnrArea ExterQual ExterCond Foundation  \
0        Wd Sdng       None         0.0        TA        TA     CBlock
1        HdBoard    BrkFace       149.0        Gd        TA     CBlock
2        HdBoard    BrkFace       149.0        Gd        TA     CBlock
3        MetalSd       None         0.0        Gd        TA     BrkTil
4        MetalSd       None         0.0        Gd        Gd     BrkTil
...          ...        ...         ...       ...       ...        ...
2402      Stucco    BrkFace       190.0        Gd        TA      PConc
2403     Wd Sdng       None         0.0        TA        TA     BrkTil
2404     Wd Sdng       None         0.0        TA        TA       Slab
2405     VinylSd    BrkFace       144.0        Gd        TA      PConc
2406     VinylSd    BrkFace       125.0        Gd        TA      PConc

     BsmtQual BsmtCond BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  \
0          TA       TA           No          Rec       238.0          Unf
1          Gd       TA           Mn          GLQ       552.0          ALQ
2          Gd       TA           Mn          GLQ       552.0          ALQ
3          TA       TA           No          ALQ       737.0          Unf
4          Fa       TA           No          Unf         0.0          Unf
...       ...      ...          ...          ...         ...          ...
2402       Gd       TA           No          Unf         0.0          Unf
2403       TA       TA           No          Unf         0.0          Unf
2404      NaN      NaN          NaN          NaN         0.0          NaN
2405       Gd       TA           No          GLQ       841.0          Unf
2406       Gd       TA           No          GLQ       380.0          Unf

      BsmtFinSF2  BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir  \
0            0.0      618.0        856.0    GasA        TA          Y
1          393.0      104.0       1049.0    GasA        TA          Y
2          393.0      104.0       1049.0    GasA        TA          Y
3            0.0      100.0        837.0    GasA        Ex          Y
4            0.0      405.0        405.0    GasA        Gd          Y
...          ...        ...          ...     ...       ...        ...
2402         0.0      796.0        796.0    GasA        Ex          Y
2403         0.0      952.0        952.0    Grav        Fa          N
2404         0.0        0.0          0.0    GasA        Ex          Y
2405         0.0      144.0        985.0    GasA        Ex          Y
2406         0.0      397.0        777.0    GasA        Ex          Y

     Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  BsmtFullBath  BsmtHalfBath  \
0         SBrkr       856         0             0           1.0           0.0
1         SBrkr      1049         0             0           1.0           0.0
2         SBrkr      1049         0             0           1.0           0.0
3         SBrkr      1001         0             0           0.0           0.0
4         SBrkr       717       322             0           0.0           0.0
...         ...       ...       ...           ...           ...           ...
2402      SBrkr       806       918             0           0.0           0.0
2403      FuseF       952         0             0           0.0           0.0
2404      FuseA      1733         0             0           0.0           0.0
2405      SBrkr       985       857             0           1.0           0.0
2406      SBrkr      1065       846             0           0.0           0.0

      FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  \
0            1         0             2             1          TA
1            2         0             2             1          Gd
2            2         0             2             1          Gd
3            1         0             2             1          Gd
4            1         0             2             1          TA
...        ...       ...           ...           ...         ...
2402         2         1             3             1          Gd
2403         1         0             2             1          Fa
2404         2         0             4             1          TA
2405         2         1             3             1          Gd
2406         2         1             3             1          Gd

      TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt  \
0                4        Typ           1          Gd     Detchd       1939.0
1                5        Typ           0         NaN     Attchd       1984.0
2                5        Typ           0         NaN     Attchd       1984.0
3                5        Typ           0         NaN     Detchd       1930.0
4                6        Typ           0         NaN     Detchd       1940.0
...            ...        ...         ...         ...        ...          ...
2402             8        Typ           1          Gd    BuiltIn       2003.0
2403             4        Typ           1          Gd     Detchd       1916.0
2404             8       Min2           1          Gd     Attchd       1955.0
2405             7        Typ           1          TA     Attchd       2000.0
2406             8        Typ           1          TA     Attchd       1993.0

     GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  \
0             Unf         2.0       399.0         TA         TA          Y
1             Fin         1.0       266.0         TA         TA          Y
2             Fin         1.0       266.0         TA         TA          Y
3             Unf         1.0       216.0         TA         Po          N
4             Unf         1.0       281.0         TA         TA          N
...           ...         ...         ...        ...        ...        ...
2402          Fin         2.0       616.0         TA         TA          Y
2403          Unf         1.0       192.0         Fa         Po          P
2404          Unf         2.0       452.0         TA         TA          Y
2405          Fin         2.0       486.0         TA         TA          Y
2406          RFn         2.0       471.0         TA         TA          Y

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
0              0            0              0          0          166
1              0          105              0          0            0
2              0          105              0          0            0
3            154            0             42         86            0
4              0            0            168          0          111
...          ...          ...            ...        ...          ...
2402         168           57              0          0            0
2403           0           98              0          0           40
2404           0            0              0          0            0
2405         193           96              0          0            0
2406         182           81              0          0            0

      PoolArea PoolQC Fence MiscFeature  MiscVal  MoSold  YrSold SaleType  \
0            0    NaN   NaN         NaN        0       3    2010      WD
1            0    NaN   NaN         NaN        0       2    2009      WD
2            0    NaN   NaN         NaN        0       2    2009      WD
3            0    NaN   NaN         NaN        0      11    2007      WD
4            0    NaN   NaN         NaN        0       5    2009      WD
...        ...    ...   ...         ...      ...     ...     ...      ...
2402         0    NaN   NaN         NaN        0       5    2006      WD
2403         0    NaN   NaN         NaN        0       5    2009      WD
2404         0    NaN   NaN         NaN        0       6    2009      WD
2405         0    NaN   NaN         NaN        0       7    2007      WD
2406         0    NaN   NaN         NaN        0       9    2006      WD

     SaleCondition  MasVnrArea2  GarageArea2  PoolArea2  HalfBath2  \
0           Normal            0          399          0        0.0
1           Normal            1          266          0        0.0
2           Normal            1          266          0        0.0
3           Normal            0          216          0        0.0
4           Normal            0          281          0        0.0
...            ...          ...          ...        ...        ...
2402        Normal            1          616          0        0.5
2403        Normal            0          192          0        0.0
2404        Normal            0          452          0        0.0
2405        Normal            1          486          0        0.5
2406        Normal            1          471          0        0.5

      BsmtHalfBath2  BasmtFinSF1  BasmtFinSF2  BasmtFinSF  total_LivArea  \
0               0.0            0            0           0            856
1               0.0          552          393         945           1994
2               0.0          552          393         945           1994
3               0.0          737            0         737           1738
4               0.0            0            0           0           1039
...             ...          ...          ...         ...            ...
2402            0.0            0            0           0           1724
2403            0.0            0            0           0            952
2404            0.0            0            0           0           1733
2405            0.0          841            0         841           2683
2406            0.0          380            0         380           2291

      num_bathroom   GeoRefNo  Tier  Range           Prop_Addr ZngCdPr  \
0              2.0  909176150     0      0     436 HAYWARD AVE      RL
1              3.0  905476230     0      0        3416 WEST ST      RL
2              3.0  905476230     0      0        3416 WEST ST      RL
3              1.0  911128020     0      0        320 S 2ND ST   S-SMD
4              1.0  535377150     0      0    1524 DOUGLAS AVE      RL
...            ...        ...   ...    ...                 ...     ...
2402           2.5  908128100     0      0    4019 MARIGOLD DR   FS-RL
2403           1.0  903205040     0      0  1021 RIDGEWOOD AVE      RL
2404           2.0  905402060     0      0       3619 MARY CIR      RL
2405           3.5  907192040     0      0   5319 CLEMENS BLVD      RL
2406           2.5  906223180     0      0     1025 VERMONT CT      RL

     ZngCdSc ZngOLPr ZngOLSc    ClassPr_S                        ClassSc_S  \
0        NaN     NaN     NaN  RESIDENTIAL             1-STORY 1945 & OLDER
1        NaN     NaN     NaN  RESIDENTIAL     1-STORY TWNHM - 1946 & NEWER
2        NaN     NaN     NaN  RESIDENTIAL     1-STORY TWNHM - 1946 & NEWER
3        NaN     NaN     NaN  RESIDENTIAL             1-STORY 1945 & OLDER
4        NaN     NaN     NaN  RESIDENTIAL             2-STORY 1945 & OLDER
...      ...     ...     ...          ...                              ...
2402     NaN     NaN     NaN  RESIDENTIAL             2-STORY 1946 & NEWER
2403     NaN     NaN     NaN  RESIDENTIAL             1-STORY 1945 & OLDER
2404     NaN     NaN     NaN  RESIDENTIAL  1-STORY 1946 & NEWER ALL STYLES
2405     NaN     NaN     NaN  RESIDENTIAL             2-STORY 1946 & NEWER
2406     NaN     NaN     NaN  RESIDENTIAL             2-STORY 1946 & NEWER

                                               Legal_Pr  SchD_S  TxD_S  \
0                  LEE & LITTLE ADD LOT 9 EX E50' BLK 2       1      1
1     WEST AMES ADD BEG NE COR LOT 12 BLK 1 S99.94' ...       1      1
2     WEST AMES ADD BEG NE COR LOT 12 BLK 1 S99.94' ...       1      1
3         BLACKS 3RD ADD E60' W125' LOT 2 & LOT 3 BLK 7       1      1
4       HARRIMAN'S ADD  AUDITOR PLAT BK 6 LOT:1 \n AMES       1      1
...                                                 ...     ...    ...
2402               SOUTH FORK SD 1ST ADD LOT:37 \n AMES       1      1
2403                       RIDGEWOOD ADD LOT:49 \n AMES       1      1
2404             REISTE'S 1ST ADD BLOCK:2 LOT:3 \n AMES       1      1
2405                  BENTWOOD SD 4TH ADD LOT:7 \n AMES       1      1
2406               VALLEY EAST PLAT NO 4 LOT:11 \n AMES       1      1

                              MA_Ownr1       MA_Ownr2             MA_Line1  \
0              GREINER, RODNEY & CELIA            NaN  2088 QUAIL RIDGE RD
1            HUBERT, JOHN F & GRETTA R            NaN         3416 WEST ST
2            HUBERT, JOHN F & GRETTA R            NaN         3416 WEST ST
3                         SKLENAR, TIM  CARNEY, SARAH         320 S 2ND ST
4                       MILLARD, TAMMY            NaN     1524 DOUGLAS AVE
...                                ...            ...                  ...
2402        LECOUNT, KAREN J & JACOB F            NaN     4019 MARIGOLD DR
2403                   KRIER, DANIEL A            NaN   1021 RIDGEWOOD AVE
2404             SCHEIBE, KEVIN & MARY            NaN      460 WESTWOOD DR
2405  POLAND, CHRISTOPHER A & ANDREA C            NaN    5319 CLEMENS BLVD
2406           SCHILTZ, JAMES & BREELY            NaN      1025 VERMONT CT

      MA_Line2 MA_City MA_State  MA_Zip1  MA_Zip2  Rcrd_Yr  Rcrd_Mo  \
0          NaN    AMES       IA    50010      NaN     2017        2
1          NaN    AMES       IA    50014   3541.0     2020        1
2          NaN    AMES       IA    50014   3541.0     2020        1
3          NaN    AMES       IA    50010   6702.0     2016        4
4          NaN    AMES       IA    50010   5314.0     2019       10
...        ...     ...      ...      ...      ...      ...      ...
2402       NaN    AMES       IA    50014      NaN     2015        5
2403       NaN    AMES       IA    50010   5827.0     2009        5
2404       NaN    AMES       IA    50014   3570.0     2009        6
2405       NaN    AMES       IA    50014   6922.0     2015        5
2406       NaN    AMES       IA    50014   3097.0     2016        6

        Inst1_No  Inst1_Yr  Inst1_Mo Inst1TPr  LndAc_S  ImpAc_S  OthAc_S  \
0     2017-01476      2017         2        D    37300        0   111700
1     2020-00358      2020         1   WRDJSV    43500        0   130600
2     2020-00358      2020         1   WRDJSV    43500        0   130600
3      201603010      2016         4   WRDJSV    41100        0   123200
4     2019-09301      2019        10      WRD    31100        0    93300
...          ...       ...       ...      ...      ...      ...      ...
2402   201504195      2015         5   WRDJSV    54700        0   163900
2403   200905543      2009         5      WRD    34600        0   103900
2404   200908586      2009         6      WRD    46300        0   138800
2405   201504675      2015         5   WRDJSV    66300        0   198900
2406   201606028      2016         6   WRDJSV    62700        0   187900

      TtlVal_AsrYr ValType X1TPr_D X1TSc_D  X2TPr_D  X2TSc_D X1TPr_S X1TSc_S  \
0           149000       F     NaN     NaN      NaN      NaN     NaN     NaN
1           174100       F     NaN     NaN      NaN      NaN     NaN     NaN
2           174100       F     NaN     NaN      NaN      NaN     NaN     NaN
3           164300       F     NaN     NaN      NaN      NaN     NaN     NaN
4           124400       F     NaN     NaN      NaN      NaN     NaN     NaN
...            ...     ...     ...     ...      ...      ...     ...     ...
2402        218600       F     NaN     NaN      NaN      NaN     NaN     NaN
2403        138500       F     NaN     NaN      NaN      NaN     NaN     NaN
2404        185100       F     NaN     NaN      NaN      NaN     NaN     NaN
2405        265200       F     NaN     NaN      NaN      NaN     NaN     NaN
2406        250600       F     NaN     NaN      NaN      NaN     NaN     NaN

      X2TPr_S  X2TSc_S  LndAcX1S  ImpAcX1S  ImpAcX2S  HSTtl_D  MilVal_D  \
0         NaN      NaN         0         0         0      NaN       NaN
1         NaN      NaN         0         0         0      NaN       NaN
2         NaN      NaN         0         0         0      NaN       NaN
3         NaN      NaN         0         0         0      NaN       NaN
4         NaN      NaN         0         0         0      NaN       NaN
...       ...      ...       ...       ...       ...      ...       ...
2402      NaN      NaN         0         0         0   4850.0       0.0

In [32]:
for test in X.columns:
    missingRows = pd.isnull(X[test]).sum(axis=1) > 0
    print(missingRows)

ValueError: No axis named 1 for object type Series

In [15]:
lasso  = Lasso()
alphas = np.linspace(0.1,20.1,20)
lasso.set_params(normalize=False)
coefs_lasso  = []

for alpha in alphas:
        lasso.set_params(alpha=alpha)
        lasso.fit(X_features, y)  
        coefs_lasso.append(lasso.coef_)

coefs_lasso = pd.DataFrame(coefs_lasso, index = alphas, columns = X.columns)  
coefs_lasso.head()

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
for name in coefs_lasso.columns:
    plt.plot(coefs_lasso.index, coefs_lasso[name], label=name)
plt.xlabel(r'hyperparameter $\lambda$')
plt.ylabel(r'slope values')
plt.legend(loc=1)